# 接続文字列。現在はURL形式のみサポート See https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html
"url" = "http://localhost:9200"
# インデックス名
"index" = "esci-products"
# スキーマファイルのパス
"schema_path" = "./schema/es/product-index-schema.json"