version: "2.2"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - ./search-engine/es/data:/usr/share/elasticsearch/data
    user: elasticsearch
    entrypoint: >
      sh -c "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji; /usr/local/bin/docker-entrypoint.sh"

